--------------------------------------------------------
-- Archivo creado  - domingo-octubre-06-2019   
--------------------------------------------------------
DROP TABLE "PDT"."REVISA" CASCADE CONSTRAINTS;
DROP TABLE "PDT"."CARACTERISTICAS" cascade constraints;
DROP TABLE "PDT"."DEPARTAMENTO" cascade constraints;
DROP TABLE "PDT"."DETALLE" cascade constraints;
DROP TABLE "PDT"."ESTADO_OBSERV" cascade constraints;
DROP TABLE "PDT"."FENOMENO" cascade constraints;
DROP TABLE "PDT"."LOCALIDAD" cascade constraints;
DROP TABLE "PDT"."OBSERVACIONES" cascade constraints;
DROP TABLE "PDT"."TELEFONO" cascade constraints;
DROP TABLE "PDT"."TIPOSUSUARIOS" cascade constraints;
DROP TABLE "PDT"."USUARIO" cascade constraints;
DROP TABLE "PDT"."ZONA" cascade constraints;

DROP SEQUENCE "PDT"."SEQ_CARACTERISTICASID";
DROP SEQUENCE "PDT"."SEQ_GEOLOCALIZACIONID";
DROP SEQUENCE "PDT"."SEQ_OBSERVACIONID";
DROP SEQUENCE "PDT"."SEQ_USUARIOID";
DROP SEQUENCE "PDT"."SEQ_CODIGOFENOMENO";
DROP SEQUENCE "PDT"."SEQ_IDLOCALIDADID";
DROP SEQUENCE "PDT"."SEQ_IDZONA";
DROP SEQUENCE "PDT"."SEQ_IDDEPARTAMENTO";
DROP SEQUENCE "PDT"."HIBERNATE_SEQUENCE";


PURGE RECYCLEBIN;
--------------------------------------------------------
--  DDL for Sequence CARACTERISTICASID
--------------------------------------------------------

   CREATE SEQUENCE  "PDT"."SEQ_CARACTERISTICASID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GEOLOCALIZACIONID
--------------------------------------------------------

   CREATE SEQUENCE  "PDT"."SEQ_GEOLOCALIZACIONID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OBSERVACIONID
--------------------------------------------------------

   CREATE SEQUENCE  "PDT"."SEQ_OBSERVACIONID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOID
--------------------------------------------------------

   CREATE SEQUENCE  "PDT"."SEQ_USUARIOID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
-- Secuencia Fenomneo
--------------------------------------------------------
	CREATE SEQUENCE "PDT"."SEQ_CODIGOFENOMENO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	
------	----------------------------------------------------
	--SECUENCIA LOCALIDAD
---	--------------------------------------------------------
	
	CREATE SEQUENCE "PDT"."SEQ_IDLOCALIDADID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

---------------------------------------------------------------
-- SECUENCIA ZONA
---------------------------------------------------------------
CREATE SEQUENCE "PDT"."SEQ_IDZONA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

---------------------------------------------------------------
-- SECUENCIA DEPARTAMENTO
----------------------------------------------------------------
CREATE SEQUENCE "PDT"."SEQ_IDDEPARTAMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

-------------------------------------------------------------------
-- secuencia que precisa jpa
-------------------------------------------------------------------
CREATE SEQUENCE "PDT"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------------------------------
-- TABLA REVISA RELACION DE EXPERTO CON OBSERVACION.
--------------------------------------------------------

CREATE TABLE "PDT"."REVISA"
(
	"ID_USUARIO" NUMBER(10),
	"ID_OBSERVACION" NUMBER(10),
	"FIABILIDAD" VARCHAR(50) not null,
	"FECHAYHORA" DATE,
	"COMENTARIOS" VARCHAR(100)
	
);

ALTER TABLE PDT.REVISA ADD CONSTRAINT PK_REVISA PRIMARY KEY (ID_OBSERVACION,ID_USUARIO,FECHAYHORA);



--------------------------------------------------------
--  DDL for Table CARACTERISTICAS
--------------------------------------------------------

  CREATE TABLE "PDT"."CARACTERISTICAS" 
   (	"ID_CARACT" NUMBER(10,0), 
	"CODIGO_FEN" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ETIQUETA" VARCHAR2(50 BYTE), 
	"TIPODATO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "PDT"."DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER(10,0), 
	"NOMBRE_DEP" VARCHAR2(40 BYTE), 
	"ID_ZONA" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE
--------------------------------------------------------

  CREATE TABLE "PDT"."DETALLE" 
   (	"ID_CARACT" NUMBER(10,0), 
	"ID_OBSERVACION" NUMBER(10,0), 
	"FECHORA" DATE, 
	"VALORNUM" NUMBER(10,0), 
	"VALORTEXTO" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADO_OBSERV
--------------------------------------------------------

  CREATE TABLE "PDT"."ESTADO_OBSERV" 
   (	"ID_ESTADO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FENOMENO
--------------------------------------------------------

  CREATE TABLE "PDT"."FENOMENO" 
   (	
   "CODIGO_FEN" NUMBER(10,0), 
   "ID_TEL" NUMBER(10,0),
   "ESTADO" VARCHAR2(50 BYTE),
   "CODIGO" VARCHAR2(40 BYTE),
	"NOMBRE_FEN" VARCHAR2(40 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCALIDAD
--------------------------------------------------------

  CREATE TABLE "PDT"."LOCALIDAD" 
   (	"ID_LOCALIDAD" NUMBER(10,0), 
	"ID_DEPARTAMENTO" NUMBER(10,0), 
	"NOMBRE_LOC" VARCHAR2(40 BYTE), 
	"LATITUD" FLOAT(50), 
	"LONGITUD" FLOAT(50), 
	"ALTITUD" FLOAT(50)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBSERVACIONES
--------------------------------------------------------

  CREATE TABLE "PDT"."OBSERVACIONES" 
   (	"ID_OBSERVACION" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0), 
	"CODIGO_FEN" NUMBER(10,0), 
	"ID_LOCALIDAD" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"IMAGEN" BLOB, 
	"LATITUD" FLOAT(50), 
	"LONGITUD" FLOAT(50), 
	"ALTITUD" FLOAT(50), 
	"ID_ESTADO" NUMBER(10,0), 
	"FECHAHORA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGEN") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TELEFONO
--------------------------------------------------------

  CREATE TABLE "PDT"."TELEFONO" 
   (	"ID_TEL" NUMBER(10,0),
	"NOMBRE" VARCHAR2(50 BYTE),
	"NUMERO" VARCHAR2(20 BYTE), 
	"CODIGO_FEN" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPOSUSUARIOS
--------------------------------------------------------

  CREATE TABLE "PDT"."TIPOSUSUARIOS" 
   (	"ID_TIPO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "PDT"."USUARIO" 
   (	"ID_USUARIO" NUMBER(10,0), 
	"ID_TIPO" NUMBER(10,0), 
	"PASS" VARCHAR2(50 	 BYTE), 
	"USUARIO" VARCHAR2(80 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"ESTADO" VARCHAR2(50 BYTE), 
	"TIPODOC" VARCHAR2(50 BYTE), 
	"NUMERODOC" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZONA
--------------------------------------------------------

  CREATE TABLE "PDT"."ZONA" 
   (	"ID_ZONA" NUMBER(10,0), 
	"NOMBRE_ZONA" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PDT.CARACTERISTICAS
SET DEFINE OFF;
REM INSERTING into PDT.DEPARTAMENTO
SET DEFINE OFF;
REM INSERTING into PDT.DETALLE
SET DEFINE OFF;
REM INSERTING into PDT.ESTADO_OBSERV
SET DEFINE OFF;
REM INSERTING into PDT.FENOMENO
SET DEFINE OFF;
REM INSERTING into PDT.LOCALIDAD
SET DEFINE OFF;
REM INSERTING into PDT.OBSERVACIONES
SET DEFINE OFF;
REM INSERTING into PDT.TELEFONO
SET DEFINE OFF;
REM INSERTING into PDT.TIPOSUSUARIOS
SET DEFINE OFF;
REM INSERTING into PDT.USUARIO
SET DEFINE OFF;
REM INSERTING into PDT.ZONA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_TELEFONO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_TELEFONO" ON "PDT"."TELEFONO" ("ID_TEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOCALIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_LOCALIDAD" ON "PDT"."LOCALIDAD" ("ID_LOCALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CODIGOFEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_CODIGOFEN" ON "PDT"."FENOMENO" ("CODIGO_FEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_USUARIO" ON "PDT"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ZONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_ZONA" ON "PDT"."ZONA" ("ID_ZONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ESTADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_ESTADO" ON "PDT"."ESTADO_OBSERV" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CARCOBSERV
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_CARCOBSERV" ON "PDT"."DETALLE" ("ID_CARACT", "ID_OBSERVACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPOUSU
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_TIPOUSU" ON "PDT"."TIPOSUSUARIOS" ("ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_IDCARACTERISTICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_IDCARACTERISTICA" ON "PDT"."CARACTERISTICAS" ("ID_CARACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
---------------------------------------------------------
-- UK- USUARIO
----------------------------------------------------------
CREATE UNIQUE INDEX "PDT"."UK_USUARIO" ON "PDT"."USUARIO" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;  
  
  
--------------------------------------------------------
--  DDL for Index UK_NOMBRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_NOMBRE" ON "PDT"."TIPOSUSUARIOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DEPARTAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_DEPARTAMENTO" ON "PDT"."DEPARTAMENTO" ("ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_NOMB_REFEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_NOMB_REFEN" ON "PDT"."FENOMENO" ("NOMBRE_FEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_IDOBSERVACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_IDOBSERVACION" ON "PDT"."OBSERVACIONES" ("ID_OBSERVACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EST_OBS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_EST_OBS" ON "PDT"."ESTADO_OBSERV" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_NOMBRE_DEP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_NOMBRE_DEP" ON "PDT"."DEPARTAMENTO" ("NOMBRE_DEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TELEFONO
--------------------------------------------------------

  ALTER TABLE "PDT"."TELEFONO" ADD CONSTRAINT "PK_TELEFONO" PRIMARY KEY ("ID_TEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."TELEFONO" MODIFY ("ID_TEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "PDT"."DEPARTAMENTO" ADD CONSTRAINT "PK_DEPARTAMENTO" PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."DEPARTAMENTO" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."DEPARTAMENTO" MODIFY ("NOMBRE_DEP" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."DEPARTAMENTO" ADD CONSTRAINT "UK_NOMBRE_DEP" UNIQUE ("NOMBRE_DEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE
--------------------------------------------------------

  ALTER TABLE "PDT"."DETALLE" ADD CONSTRAINT "PK_CARCOBSERV" PRIMARY KEY ("ID_CARACT", "ID_OBSERVACION","FECHORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."DETALLE" MODIFY ("ID_CARACT" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."DETALLE" MODIFY ("ID_OBSERVACION" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."DETALLE" MODIFY ("VALORNUM" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."DETALLE" MODIFY ("VALORTEXTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOSUSUARIOS
--------------------------------------------------------

  ALTER TABLE "PDT"."TIPOSUSUARIOS" ADD CONSTRAINT "PK_TIPOUSU" PRIMARY KEY ("ID_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."TIPOSUSUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."TIPOSUSUARIOS" ADD CONSTRAINT "UK_NOMBRE" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PDT"."USUARIO" ADD CONSTRAINT "MAIL_CHECK" CHECK (MAIL LIKE '%@%._%') ENABLE;
 
  ALTER TABLE "PDT"."USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."USUARIO" MODIFY ("PASS" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."USUARIO" MODIFY ("USUARIO" NOT NULL ENABLE);
 
  
 
  ALTER TABLE "PDT"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."USUARIO" MODIFY ("TIPODOC" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."USUARIO" MODIFY ("NUMERODOC" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."USUARIO" MODIFY ("DIRECCION" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."USUARIO" ADD CONSTRAINT "TIPODOC_CHECK" CHECK (TIPODOC ='CI' or TIPODOC = 'PASAPORTE' or TIPODOC='CARTA DE CIUDADANIA' or  TIPODOC='OTROS') ENABLE;
  
<<<<<<< Updated upstream
  ALTER TABLE "PDT"."USUARIO" ADD CONSTRAINT "ESTADO_CHECK" CHECK (ESTADO ='ACTIVO' or ESTADO = 'INACTIVO' or ESTADO='BLOQUEADO') ENABLE;
=======
  ALTER TABLE "PDT"."USUARIO" ADD CONSTRAINT "ESTADO_CHECK" CHECK (ESTADO ='BLOQUEADO' or ESTADO = 'ACTIVO' or ESTADO='INACTIVO') ENABLE;
>>>>>>> Stashed changes
--------------------------------------------------------
--  Constraints for Table ZONA
--------------------------------------------------------

  ALTER TABLE "PDT"."ZONA" ADD CONSTRAINT "PK_ZONA" PRIMARY KEY ("ID_ZONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."ZONA" MODIFY ("ID_ZONA" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."ZONA" MODIFY ("NOMBRE_ZONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARACTERISTICAS
--------------------------------------------------------

  ALTER TABLE "PDT"."CARACTERISTICAS" ADD CONSTRAINT "PK_IDCARACTERISTICA" PRIMARY KEY ("ID_CARACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."CARACTERISTICAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."CARACTERISTICAS" MODIFY ("ETIQUETA" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."CARACTERISTICAS" MODIFY ("TIPODATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO_OBSERV
--------------------------------------------------------

  ALTER TABLE "PDT"."ESTADO_OBSERV" ADD CONSTRAINT "PK_EST_OBS" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."ESTADO_OBSERV" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."ESTADO_OBSERV" ADD CONSTRAINT "UK_ESTADO" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBSERVACIONES
--------------------------------------------------------

  ALTER TABLE "PDT"."OBSERVACIONES" ADD CONSTRAINT "PK_IDOBSERVACION" PRIMARY KEY ("ID_OBSERVACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."OBSERVACIONES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."OBSERVACIONES" MODIFY ("LATITUD" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."OBSERVACIONES" MODIFY ("LONGITUD" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."OBSERVACIONES" MODIFY ("ALTITUD" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."OBSERVACIONES" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FENOMENO
--------------------------------------------------------

  ALTER TABLE "PDT"."FENOMENO" ADD CONSTRAINT "PK_CODIGOFEN" PRIMARY KEY ("CODIGO_FEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."FENOMENO" MODIFY ("CODIGO_FEN" NOT NULL ENABLE);
  
  ALTER TABLE "PDT"."FENOMENO" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."FENOMENO" MODIFY ("NOMBRE_FEN" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."FENOMENO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."FENOMENO" ADD CONSTRAINT "UK_NOMB_REFEN" UNIQUE ("NOMBRE_FEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  
  ALTER TABLE "PDT"."FENOMENO" ADD CONSTRAINT "ESTADO_CHECKFENOMENO" CHECK (ESTADO ='ACTIVO' or ESTADO = 'INACTIVO' or ESTADO='BLOQUEADO') ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCALIDAD
--------------------------------------------------------

  ALTER TABLE "PDT"."LOCALIDAD" ADD CONSTRAINT "PK_LOCALIDAD" PRIMARY KEY ("ID_LOCALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDT"."LOCALIDAD" MODIFY ("ID_LOCALIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."LOCALIDAD" MODIFY ("NOMBRE_LOC" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."LOCALIDAD" MODIFY ("LATITUD" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."LOCALIDAD" MODIFY ("LONGITUD" NOT NULL ENABLE);
 
  ALTER TABLE "PDT"."LOCALIDAD" MODIFY ("ALTITUD" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CARACTERISTICAS
--------------------------------------------------------

  ALTER TABLE "PDT"."CARACTERISTICAS" ADD CONSTRAINT "FK_CARAC_FENOMENO" FOREIGN KEY ("CODIGO_FEN")
	  REFERENCES "PDT"."FENOMENO" ("CODIGO_FEN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "PDT"."DEPARTAMENTO" ADD CONSTRAINT "FK_IDZONA" FOREIGN KEY ("ID_ZONA")
	  REFERENCES "PDT"."ZONA" ("ID_ZONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE
--------------------------------------------------------

  ALTER TABLE "PDT"."DETALLE" ADD CONSTRAINT "FK_CARAC_DETALLE" FOREIGN KEY ("ID_CARACT")
	  REFERENCES "PDT"."CARACTERISTICAS" ("ID_CARACT") ENABLE;
 
  ALTER TABLE "PDT"."DETALLE" ADD CONSTRAINT "FK_OBSERVACION_DETALLE" FOREIGN KEY ("ID_OBSERVACION")
	  REFERENCES "PDT"."OBSERVACIONES" ("ID_OBSERVACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table R
--------------------------------------------------------
ALTER TABLE "PDT"."REVISA" ADD CONSTRAINT "FK_EX_REV_" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PDT"."USUARIO" ("ID_USUARIO") ENABLE;
 
ALTER TABLE "PDT"."REVISA" ADD CONSTRAINT "FK_REV_OBS" FOREIGN KEY ("ID_OBSERVACION")
	  REFERENCES "PDT"."OBSERVACIONES" ("ID_OBSERVACION") ENABLE;
-----------------------------------------------------------------------------------------------
--Ref Constraints for Table Fenomeno
----------------------------------------------------------------------------------------------
 ALTER TABLE "PDT"."FENOMENO" ADD CONSTRAINT "FK_TEL_FENOMENOS" FOREIGN KEY ("ID_TEL")
	  REFERENCES "PDT"."TELEFONO" ("ID_TEL") ENABLE;


--------------------------------------------------------

--  Ref Constraints for Table LOCALIDAD
--------------------------------------------------------

  ALTER TABLE "PDT"."LOCALIDAD" ADD CONSTRAINT "FK_LOCA_DPTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "PDT"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBSERVACIONES
--------------------------------------------------------

  ALTER TABLE "PDT"."OBSERVACIONES" ADD CONSTRAINT "FK_ESTADO_OBS" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "PDT"."ESTADO_OBSERV" ("ID_ESTADO") ENABLE;
 
  ALTER TABLE "PDT"."OBSERVACIONES" ADD CONSTRAINT "FK_LOCALOBSERV" FOREIGN KEY ("ID_LOCALIDAD")
	  REFERENCES "PDT"."LOCALIDAD" ("ID_LOCALIDAD") ENABLE;
 
  ALTER TABLE "PDT"."OBSERVACIONES" ADD CONSTRAINT "FK_OBSFENOMENO" FOREIGN KEY ("CODIGO_FEN")
	  REFERENCES "PDT"."FENOMENO" ("CODIGO_FEN") ENABLE;
 
  ALTER TABLE "PDT"."OBSERVACIONES" ADD CONSTRAINT "FK_USU_OBSERVACION" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PDT"."USUARIO" ("ID_USUARIO") ENABLE;
	  

--------------------------------------------------------
--  Ref Constraints for Table TELEFONO
--------------------------------------------------------

 -- ALTER TABLE "PDT"."TELEFONO" ADD CONSTRAINT "FK_TEL_FENOMENO" FOREIGN KEY ("CODIGO_FEN")
	--  REFERENCES "PDT"."FENOMENO" ("CODIGO_FEN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PDT"."USUARIO" ADD CONSTRAINT "FK_USU_TIPO" FOREIGN KEY ("ID_TIPO")
	  REFERENCES "PDT"."TIPOSUSUARIOS" ("ID_TIPO") ENABLE;
	  
	  
	  
--------------------------------------------------------
--  DDL for Trigger TRIOBSERVACION
--------------------------------------------------------

 /*CREATE OR REPLACE TRIGGER "PDT"."TRIOBSERVACION" BEFORE  ON PDT.OBSERVACIONES   FOR EACH ROW 
BEGIN SELECT SEQ_OBSERVACIONID.NEXTVAL INTO :new.ID_OBSERVACION FROM DUAL;  
 END;
 
/
ALTER TRIGGER "PDT"."TRIOBSERVACION" ENABLE;*/
--------------------------------------------------------
--  DDL for Trigger TRIUSUARIOID
--------------------------------------------------------

 /* CREATE OR REPLACE TRIGGER "PDT"."TRIUSUARIOID" BEFORE INSERT ON PDT.USUARIO   FOR EACH ROW 
BEGIN SELECT SEQ_USUARIOID.NEXTVAL INTO :new.ID_USUARIO FROM DUAL; 
END;
/
ALTER TRIGGER "PDT"."TRIUSUARIOID" ENABLE;*/
--------------------------------------------------------
--  DDL for Trigger TTRICARACTERISTICAS
--------------------------------------------------------

 /* CREATE OR REPLACE TRIGGER "PDT"."TTRICARACTERISTICAS" BEFORE INSERT ON PDT.CARACTERISTICAS   FOR EACH ROW 
BEGIN SELECT SEQ_CARACTERISTICASID.NEXTVAL INTO :new.ID_CARACT FROM DUAL;
 END;
/
ALTER TRIGGER "PDT"."TTRICARACTERISTICAS" ENABLE;
*/


--------------------------------------------------------
--  DDL for Trigger TRIFENOMENO
--------------------------------------------------------

 /* CREATE OR REPLACE TRIGGER "PDT"."TRIFENOMENO" BEFORE INSERT ON PDT.FENOMENO   FOR EACH ROW 
BEGIN SELECT SEQ_CODIGOFENOMENO.NEXTVAL INTO :new.CODIGO_FEN FROM DUAL;
 END;
/
ALTER TRIGGER "PDT"."TRIFENOMENO" ENABLE;

*/
--------------------------------------------------------
--  DDL for Trigger TRIZONA
--------------------------------------------------------

 /* CREATE OR REPLACE TRIGGER "PDT"."TRIZONA" BEFORE INSERT ON PDT.ZONA   FOR EACH ROW 
BEGIN SELECT SEQ_IDZONA.NEXTVAL INTO :new.ID_ZONA FROM DUAL;
 END;
/
ALTER TRIGGER "PDT"."TRIZONA" ENABLE;

*/
--------------------------------------------------------
--  DDL for Trigger TRILOCALIDAD
--------------------------------------------------------

 /* CREATE OR REPLACE TRIGGER "PDT"."TRILOCALIDAD" BEFORE INSERT ON PDT.LOCALIDAD   FOR EACH ROW 
BEGIN SELECT SEQ_IDLOCALIDADID.NEXTVAL INTO :new.ID_LOCALIDAD FROM DUAL;
 END;
/
ALTER TRIGGER "PDT"."TRILOCALIDAD" ENABLE;
*/

--------------------------------------------------------
--  DDL for Trigger TRIDEPARTAMENTO
--------------------------------------------------------
/*
  CREATE OR REPLACE TRIGGER "PDT"."TRIDEPARTAMENTO" BEFORE INSERT ON PDT.DEPARTAMENTO   FOR EACH ROW 
BEGIN SELECT SEQ_IDDEPARTAMENTO.NEXTVAL INTO :new.ID_DEPARTAMENTO FROM DUAL;
 END;
/
ALTER TRIGGER "PDT"."TRILOCALIDAD" ENABLE;


*/





----------------------------------------------------------------------



--INSERT DE ZONAS
INSERT INTO ZONA (ID_ZONA, NOMBRE_ZONA) VALUES (1, 'ESTE');
INSERT INTO ZONA (ID_ZONA, NOMBRE_ZONA) VALUES (2, 'OESTE');
INSERT INTO ZONA (ID_ZONA, NOMBRE_ZONA) VALUES (3, 'NORTE');
INSERT INTO ZONA (ID_ZONA, NOMBRE_ZONA) VALUES (4, 'SUR');


--INSERT DE TIPOS DE USUARIOS
INSERT INTO TIPOSUSUARIOS(ID_TIPO, NOMBRE) VALUES (1, 'ADMINISTRADOR');
INSERT INTO TIPOSUSUARIOS(ID_TIPO, NOMBRE) VALUES (2, 'EXPERTO');
INSERT INTO TIPOSUSUARIOS(ID_TIPO, NOMBRE) VALUES (3, 'VOLUNTARIO');


--INSERT DE DEPARTAMENTOS
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (1, 'ARTIGAS',3);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (2, 'SALTO',3);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (3, 'PAYSANDO',3);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (4, 'RIO NEGRO',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (5, 'SORIANO',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (6, 'COLONIA',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (7, 'RIVERA',3);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (8, 'TACUAREMBO',3);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (9, 'DURAZNO',4);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (10, 'FLORES',4);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (11, 'LAVALLEJA',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (12, 'CERRO LARGO',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (13, 'SAN JOSE',4);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (14, 'CANELONES',4);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (15, 'TREINTA Y TRES',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (16, 'MALDONADO',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (17, 'MONTEVIDEO',4);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (18, 'ROCHA',1);
INSERT INTO DEPARTAMENTO(ID_DEPARTAMENTO, NOMBRE_DEP, ID_ZONA) VALUES (19, 'FLORIDA',4);


--INSERT DE LOCALIDADES
INSERT INTO LOCALIDAD(ID_LOCALIDAD, ID_DEPARTAMENTO, NOMBRE_LOC, LATITUD, LONGITUD,ALTITUD) 
VALUES(1,14,'LAS PIEDRAS',34.716667, 56.216667, 81);
INSERT INTO LOCALIDAD(ID_LOCALIDAD, ID_DEPARTAMENTO, NOMBRE_LOC, LATITUD, LONGITUD,ALTITUD) 
VALUES(2,6,'COLONIA DEL SACRAMENTO',34.471389, 57.844167, 27);
INSERT INTO LOCALIDAD(ID_LOCALIDAD, ID_DEPARTAMENTO, NOMBRE_LOC, LATITUD, LONGITUD,ALTITUD) 
VALUES(3,5,'MERCEDES',33.25, 58.031944, 20);
INSERT INTO LOCALIDAD(ID_LOCALIDAD, ID_DEPARTAMENTO, NOMBRE_LOC, LATITUD, LONGITUD,ALTITUD) 
VALUES(4,11,'MINAS',34.366667, 55.233333, 140);


--INSERTS PARA TELEFONOS
INSERT INTO TELEFONO(ID_TEL, NOMBRE,NUMERO, CODIGO_FEN) VALUES (1,'RESCATE', 911, 1);
INSERT INTO TELEFONO(ID_TEL, NOMBRE,NUMERO, CODIGO_FEN) VALUES (2, 'BOMBEROS',08007474, 2);
INSERT INTO TELEFONO(ID_TEL, NOMBRE,NUMERO, CODIGO_FEN) VALUES (3, 'SEMENTAL',23658855, 3);
INSERT INTO TELEFONO(ID_TEL, NOMBRE,NUMERO, CODIGO_FEN) VALUES (4, 'BRUNO',23657448, 3);


--INSERTS PARA FENOMENOS
INSERT INTO FENOMENO(CODIGO_FEN,CODIGO,ESTADO, NOMBRE_FEN, DESCRIPCION,ID_TEL) VALUES(1,'AA54','ACTIVO', 'GRANIZO', 'TIPO DE PRECIPITACION SOLIDA QUE SE COMPONE DE HIELO',1);
INSERT INTO FENOMENO(CODIGO_FEN,CODIGO,ESTADO, NOMBRE_FEN, DESCRIPCION,ID_TEL) VALUES(2,'AA43','ACTIVO','HURACAN', 'GRAN TORMENTA TROPICAL CARACTERIZADA POR GRANDES VIENTOS',2);
<<<<<<< Updated upstream
INSERT INTO FENOMENO(CODIGO_FEN,CODIGO,ESTADO, NOMBRE_FEN, DESCRIPCION,ID_TEL) VALUES(3, 'SSS5','INACTIVO' ,'TORNADO','COLUMNA DE AIRE CON GRAN VELOCIDAD ANGULAR',3);
=======
INSERT INTO FENOMENO(CODIGO_FEN,CODIGO,ESTADO, NOMBRE_FEN, DESCRIPCION,ID_TEL) VALUES(3, 'SSS5','BLOQUEADO' ,'TORNADO','COLUMNA DE AIRE CON GRAN VELOCIDAD ANGULAR',3);
>>>>>>> Stashed changes
INSERT INTO FENOMENO(CODIGO_FEN,CODIGO,ESTADO, NOMBRE_FEN, DESCRIPCION,ID_TEL) VALUES(4, 'DS','ACTIVO','TSUNAMI', 'EVENTO QUIE INVOLUCRA GRANDES OLAS DE GRAN ENERGIA Y TAMAÑO',4);


--INSERT PARA CARACTERISTICAS
INSERT INTO CARACTERISTICAS(ID_CARACT, CODIGO_FEN, NOMBRE, ETIQUETA, TIPODATO)
VALUES(1, 1, 'GRANIZADO', 'TORMENTA', 'INFORMATIVO');
INSERT INTO CARACTERISTICAS(ID_CARACT, CODIGO_FEN, NOMBRE, ETIQUETA, TIPODATO)
VALUES(2, 2, 'VIENTOS Y LLUVIAS', 'TORMENTA', 'INFORMATIVO');
INSERT INTO CARACTERISTICAS(ID_CARACT, CODIGO_FEN, NOMBRE, ETIQUETA, TIPODATO)
VALUES(3, 2, 'VIENTO', 'SOPLA', 'ALERTA');
INSERT INTO CARACTERISTICAS(ID_CARACT, CODIGO_FEN, NOMBRE, ETIQUETA, TIPODATO)
VALUES(4, 4, 'OLA GIGANTE', 'SUPER-OLA', 'PELIGRO');

--INSERTS PARA ESTADOS
INSERT INTO ESTADO_OBSERV(ID_ESTADO, NOMBRE) VALUES (1, 'ACTIVO');
INSERT INTO ESTADO_OBSERV(ID_ESTADO, NOMBRE) VALUES (2, 'INACTIVO');
INSERT INTO ESTADO_OBSERV(ID_ESTADO, NOMBRE) VALUES (3, 'BLOQUEADO');


--INSERTS PARA USUARIOS
INSERT INTO USUARIO(ID_USUARIO, ID_TIPO, PASS, USUARIO, NOMBRE, APELLIDO, ESTADO, TIPODOC, NUMERODOC, DIRECCION, MAIL)
<<<<<<< Updated upstream
VALUES(1, 1, 'ADMIN', 'ADMIN', 'ADMINISTRATOR', 'TOTAL', 'ACTIVO','CI', '54025652', 'CONSTITUYENTE 1740', 'RICARDO.BOZ@ESTUDIANTES.UTEC.EDU.UY');
INSERT INTO USUARIO(ID_USUARIO, ID_TIPO, PASS, USUARIO, NOMBRE, APELLIDO, ESTADO, TIPODOC, NUMERODOC, DIRECCION, MAIL)
VALUES(2, 2, 'PASSWORD', 'USER', 'VOLUNTARY', 'FREE', 'ACTIVO','PASAPORTE', 'ASP4488', '18 DE JULIO 115', 'PRUEBA.PRUEBA@HOTMAIL.COM');
INSERT INTO USUARIO(ID_USUARIO, ID_TIPO, PASS, USUARIO, NOMBRE, APELLIDO, ESTADO, TIPODOC, NUMERODOC, DIRECCION, MAIL)
VALUES(3, 3, 'EXPERTO', 'EXPERTO', 'EXPERT', 'PAYMENT', 'ACTIVO','OTROS', '54025652', 'P SHERMAN CALLE WALLABY 42', 'EXPERTO@GMAIL.COM');
=======
VALUES(4, 3, 'admin', 'admin', 'ADMINISTRATOR', 'TOTAL', 'ACTIVO','CI', '54025652', 'CONSTITUYENTE 1740', 'ricardo.boz@estudiantes.utec.edu.uy');
INSERT INTO USUARIO(ID_USUARIO, ID_TIPO, PASS, USUARIO, NOMBRE, APELLIDO, ESTADO, TIPODOC, NUMERODOC, DIRECCION, MAIL)
VALUES(2, 2, 'password', 'user', 'VOLUNTARY', 'FREE', 'BLOQUEADO','PASAPORTE', 'ASP4488', '18 DE JULIO 115', 'PRUEBA.PRUEBA@HOTMAIL.COM');
INSERT INTO USUARIO(ID_USUARIO, ID_TIPO, PASS, USUARIO, NOMBRE, APELLIDO, ESTADO, TIPODOC, NUMERODOC, DIRECCION, MAIL)
VALUES(3, 3, 'experto', 'experto', 'EXPERT', 'PAYMENT', 'INACTIVO','OTROS', '54025652', 'P SHERMAN CALLE WALLABY 42', 'EXPERTO@GMAIL.COM');
>>>>>>> Stashed changes


--INSERTS PARA OBSERVACIONES
INSERT INTO OBSERVACIONES(ID_OBSERVACION, ID_USUARIO, CODIGO_FEN, ID_LOCALIDAD, DESCRIPCION, IMAGEN, LATITUD, LONGITUD, ALTITUD, ID_ESTADO, FECHAHORA)
  VALUES(1, 2, 1, 1, 'MUY INTENSA LA GRANIZADA POR AQUI', EMPTY_BLOB(), 37.5, 55.1, 33, 1, TO_DATE('2018/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO OBSERVACIONES(ID_OBSERVACION, ID_USUARIO, CODIGO_FEN, ID_LOCALIDAD, DESCRIPCION, IMAGEN, LATITUD, LONGITUD, ALTITUD, ID_ESTADO, FECHAHORA)
  VALUES(2, 2, 2, 3, 'MUCHO VIENTO', EMPTY_BLOB(), 37.6, 55.135, 34, 1, TO_DATE('2019/10/28 19:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO OBSERVACIONES(ID_OBSERVACION, ID_USUARIO, CODIGO_FEN, ID_LOCALIDAD, DESCRIPCION, IMAGEN, LATITUD, LONGITUD, ALTITUD, ID_ESTADO, FECHAHORA)
  VALUES(3, 1, 3, 2, 'SE VUELA TODO!!', EMPTY_BLOB(), 38.5, 56.15, 26, 1, TO_DATE('2019/10/27 18:02:44', 'yyyy/mm/dd hh24:mi:ss'));



--INSERT PARA DETALLES
INSERT INTO DETALLE(ID_CARACT, ID_OBSERVACION, FECHORA, VALORNUM, VALORTEXTO)
VALUES(1,1,TO_DATE('2019/10/24 18:02:44', 'yyyy/mm/dd hh24:mi:ss'), 10, 'EXCELENTE DETALLE DE OBSERVACION');
INSERT INTO DETALLE(ID_CARACT, ID_OBSERVACION, FECHORA, VALORNUM, VALORTEXTO)
VALUES(2,2,TO_DATE('2019/10/23 18:02:44', 'yyyy/mm/dd hh24:mi:ss'), 44, 'OTRO DETALLE DE OBSERVACION');
INSERT INTO DETALLE(ID_CARACT, ID_OBSERVACION, FECHORA, VALORNUM, VALORTEXTO)
VALUES(3,3,TO_DATE('2019/10/22 18:02:44', 'yyyy/mm/dd hh24:mi:ss'), 115, 'ULTIMO DETALLE DE OBSERVACION');


INSERT INTO REVISA(ID_USUARIO, ID_OBSERVACION, FIABILIDAD, FECHAYHORA, COMENTARIOS)
VALUES(1,1,'BAJA',TO_DATE('2019/10/22 18:02:44', 'yyyy/mm/dd hh24:mi:ss'),'NADA QUE AGREGAR');
INSERT INTO REVISA(ID_USUARIO, ID_OBSERVACION, FIABILIDAD, FECHAYHORA, COMENTARIOS)
VALUES(2,2,'MEDIA',TO_DATE('2019/10/23 18:02:44', 'yyyy/mm/dd hh24:mi:ss'),'SIN COMENTARIOS');
INSERT INTO REVISA(ID_USUARIO, ID_OBSERVACION, FIABILIDAD, FECHAYHORA, COMENTARIOS)
VALUES(3,3,'ALTA',TO_DATE('2019/10/24 18:02:44', 'yyyy/mm/dd hh24:mi:ss'),'EXTRAOFICIAL?');




select * from ZONA;
select * from TIPOSUSUARIOS;
select * from DEPARTAMENTO;
select * from LOCALIDAD;
select * from FENOMENO;
select * from CARACTERISTICAS;
select * from ESTADO_OBSERV;
SELECT * FROM TELEFONO;
SELECT * FROM USUARIO;
SELECT * FROM OBSERVACIONES;
SELECT * FROM DETALLE;
SELECT * FROM REVISA;


